@jwtToken =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuVmVyc2lvbiI6MSwiaWF0IjoxNzcyODc3MDUzLCJleHAiOjE3NzI4ODQyNTN9.Y7-C5KhJRtpgqSl5P9OyU3lByCMAVCDZf-WyBpgYE-1YTU3bL0DA14evhbxUScDvI2V14AQMt2WBT7UXBc_gYw

### 登录
POST http://localhost:5603/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin@123"
}

### 获取用户信息
GET http://localhost:5603/auth/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}