@jwtToken =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzcyODc2MzQ0LCJleHAiOjE3NzI4ODM1NDR9.69FEieV8Y8BP-GVkIURFu9QNVBp4vomadCScRSIyhiM-gk4q9by36bpPco1yorERrcv88CdZQ-PlvjEdPV55aQ

### 登录
POST http://localhost:5603/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin@123"
}

### 获取用户信息
GET http://localhost:5603/auth/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}